[package]
name = "aero-codex-flight-dynamics"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[lib]
name = "aero_codex_flight_dynamics"
path = "src/lib.rs"

[dependencies]
aero-codex-core = { version = "=0.1.0-alpha.1", path = "../aero-codex-core" }

[lints]
workspace = true
